version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fastapi_auth
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: your_password_here
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create_database.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://fastapi_user:your_password_here@db:5432/fastapi_auth
      SECRET_KEY: your-super-secret-key-change-this-in-production
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
